export const MAX_YOUTUBE_DURATION_SECONDS = 15 * 60;
export const MAX_YOUTUBE_DURATION_LABEL = "15 minutes";

export const MAX_YOUTUBE_AUDIO_BYTES = 25 * 1024 * 1024;
export const MAX_YOUTUBE_AUDIO_LABEL = "25 MB";

export const MAX_YOUTUBE_DOWNLOAD_BYTES = 25 * 1024 * 1024;
export const MAX_YOUTUBE_DOWNLOAD_LABEL = "25 MB";
